version: '3'

services:

  nginx:
    depends_on: 
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  server:
    env_file:
        "./server/.env"
    build:
      dockerfile: Dockerfile
      context: ./server

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client