version: '3'

services:

  nginx:
    depends_on: 
      - api
      - client
    restart: always
    build:
      dockefile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  backend:
    env_file:
        "./backend/.env"
    build:
      dockerfile: Dockerfile
      context: ./backend

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend