version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "patrem98/deepc-fish-name-generator"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "patrem98/deepc-fish-name-generator"
    ports:
      - "3000:3000"
    links:
      - "backend" #Use the service name here, not the container name or id